/*
*  MODEL _ 
*  ITEMS
*/
const SQL = require('sql-template-strings');
const dbPromise = require("../database/database");
const moment = require("moment");
const debug = require("debug");

//debug namespace
const itemDAO = debug('devLog:itemDAO');

/** Creates a new ITEM
* @param item, the item to insert into the database 
* 
*/


async function createItem(item) {
  itemDAO("creating item");
  const db = await dbPromise;
  const created_at = moment(new (Date)).format('YYYY-MM-DD HH:mm:ss');
  const result = await db.run(SQL`INSERT INTO items (
    item_id,
    created_at, 
    barcode,
    item_name,
    item_descrption,
    item_cost,
    item_UOM,
    item_quantity) VALUES (
    ${item_id},
    ${created_at},
    ${item.barcode},
    ${item.name},
    ${item.description},
    ${item.cost},
    ${item.Uom},
    ${item.qty}
    );`);
  // get the id generated by the db and assign it back to the user object
  item.id = result.lastID;
  itemDAO(item.id)
  return item
};


module.exports = {
  createItem: createItem,
  retrieveItemWithId,
  retrieveItemWithSearchString,
  updateItemWithId,
  deleteItemWithId
};